name: CI Build

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Use Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - run: npm ci
      - run: npm run build